### ISSUE TITLE
where are the txt data files for training auto encoders

### ISSUE THREAD

**Issue by xylophone234** [XingxingZhang/dress#3]
in file train_atuo_encoder.sh

where  are the files?

train=/afs/inf.ed.ac.uk/group/project/img2txt/encdec/dataset/wiki-full/norm_all/auto-encoder-data/train.txt
valid=/afs/inf.ed.ac.uk/group/project/img2txt/encdec/dataset/wiki-full/norm_all/auto-encoder-data/valid.txt
test=/afs/inf.ed.ac.uk/group/project/img2txt/encdec/dataset/wiki-full/norm_all/auto-encoder-data/test.txt

**Comment by XingxingZhang** [comment]
"We use a sequence auto-encoder (SAE; Dai and Le 2015) to train the LSTM sentence encoder on both the complex and simple sentences."

So you can simply concatenate train/valid/test.src and train/valid/test.dst to train/valid/test.txt.
But please do remember to exclude sentences in valid/test sets from training. Usually there shouldn't be any such sentences, but you should always check that.

Here is an example script https://github.com/XingxingZhang/dress/blob/master/scripts/get_auto_encoder_data/gen_data.sh
